package com.example.payrollsheet.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import android.widget.Toast
import androidx.core.content.FileProvider
import com.example.payrollsheet.ui.screens.UnifiedSummaryEntry
import java.io.File
import java.io.FileOutputStream
import java.io.OutputStreamWriter
import java.nio.charset.StandardCharsets
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

object CsvExporter {

    /**
     * Generates a formatted CSV string representing the payroll summary entries,
     * including column headers and an accounting summary row at the bottom.
     */
    fun generatePayrollSummaryCsv(
        entries: List<UnifiedSummaryEntry>,
        periodTitle: String
    ): String {
        val sb = StringBuilder()

        // CSV Header Metadata for Accountants & Auditors
        sb.append("# SITE PAYROLL SHEET - MONTHLY DISBURSEMENT SUMMARY\n")
        sb.append("# Accounting Period: ").append(escapeCsv(periodTitle)).append("\n")
        sb.append("# Generated on: ").append(SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).format(Date())).append("\n")
        sb.append("# Currency: QAR (Qatari Riyal)\n")
        sb.append("\n")

        // Table Column Headers
        val headers = listOf(
            "Emp ID",
            "Badge No",
            "Employee Name",
            "Trade / Role",
            "Month",
            "Hours Worked",
            "Hourly Rate (QAR)",
            "Gross Salary (QAR)",
            "Deductions (QAR)",
            "Net Salary (QAR)",
            "Paid Amount (QAR)",
            "Balance Due (QAR)",
            "Payment Date",
            "Payment Status",
            "Payment Method",
            "Notes / Site Reference"
        )
        sb.append(headers.joinToString(",") { escapeCsv(it) }).append("\n")

        var totalHours = 0.0
        var totalGross = 0.0
        var totalDeductions = 0.0
        var totalNet = 0.0
        var totalPaid = 0.0
        var totalBalance = 0.0

        // Data Rows
        entries.forEach { entry ->
            val balance = maxOf(0.0, entry.netSalary - entry.paidAmount)
            totalHours += entry.hoursWorked
            totalGross += entry.grossSalary
            totalDeductions += entry.deductions
            totalNet += entry.netSalary
            totalPaid += entry.paidAmount
            totalBalance += balance

            val row = listOf(
                entry.employeeId.toString(),
                entry.employeeIdNumber,
                entry.employeeName,
                entry.employeeTrade,
                entry.month,
                String.format(Locale.US, "%.1f", entry.hoursWorked),
                String.format(Locale.US, "%.2f", entry.hourlyRate),
                String.format(Locale.US, "%.2f", entry.grossSalary),
                String.format(Locale.US, "%.2f", entry.deductions),
                String.format(Locale.US, "%.2f", entry.netSalary),
                String.format(Locale.US, "%.2f", entry.paidAmount),
                String.format(Locale.US, "%.2f", balance),
                entry.paymentDate,
                entry.paymentStatus,
                entry.paymentMethod,
                entry.notes
            )
            sb.append(row.joinToString(",") { escapeCsv(it) }).append("\n")
        }

        // Summary Accounting Row
        sb.append("\n")
        val summaryRow = listOf(
            "TOTAL SUMMARY",
            "${entries.size} Employees",
            "",
            "",
            periodTitle,
            String.format(Locale.US, "%.1f", totalHours),
            "-",
            String.format(Locale.US, "%.2f", totalGross),
            String.format(Locale.US, "%.2f", totalDeductions),
            String.format(Locale.US, "%.2f", totalNet),
            String.format(Locale.US, "%.2f", totalPaid),
            String.format(Locale.US, "%.2f", totalBalance),
            "-",
            "AUDITED",
            "-",
            "Auto-generated by Site Payroll Accounting"
        )
        sb.append(summaryRow.joinToString(",") { escapeCsv(it) }).append("\n")

        return sb.toString()
    }

    /**
     * Escapes fields containing commas, quotes, or newlines per RFC 4180.
     */
    private fun escapeCsv(value: String): String {
        return if (value.contains(",") || value.contains("\"") || value.contains("\n") || value.contains("\r")) {
            "\"" + value.replace("\"", "\"\"") + "\""
        } else {
            value
        }
    }

    /**
     * Writes CSV string to the specified Uri selected by the user via the Storage Access Framework
     */
    fun writeCsvToUri(context: Context, uri: Uri, csvContent: String): Boolean {
        return try {
            context.contentResolver.openOutputStream(uri)?.use { outputStream ->
                OutputStreamWriter(outputStream, StandardCharsets.UTF_8).use { writer ->
                    writer.write(csvContent)
                    writer.flush()
                }
            }
            Toast.makeText(context, "Payroll summary CSV saved successfully!", Toast.LENGTH_LONG).show()
            true
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Failed to save CSV: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
            false
        }
    }

    /**
     * Saves CSV file to app cache directory and launches Android share sheet
     */
    fun shareCsvFile(context: Context, filename: String, csvContent: String) {
        try {
            val exportDir = File(context.cacheDir, "payroll_exports")
            if (!exportDir.exists()) {
                exportDir.mkdirs()
            }
            val file = File(exportDir, filename)
            FileOutputStream(file).use { fos ->
                OutputStreamWriter(fos, StandardCharsets.UTF_8).use { writer ->
                    writer.write(csvContent)
                    writer.flush()
                }
            }

            val fileUri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/csv"
                putExtra(Intent.EXTRA_STREAM, fileUri)
                putExtra(Intent.EXTRA_SUBJECT, "Payroll Summary Export - $filename")
                putExtra(Intent.EXTRA_TEXT, "Attached is the monthly payroll summary CSV export for accounting.")
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }

            val chooser = Intent.createChooser(shareIntent, "Export Payroll Summary CSV")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
        } catch (e: Exception) {
            e.printStackTrace()
            Toast.makeText(context, "Could not share CSV: ${e.localizedMessage}", Toast.LENGTH_LONG).show()
        }
    }
}
